#!/usr/bin/env python3
"""Generate compressed, byte-exact local Web fragments for the irrigation firmware."""

from __future__ import annotations

import argparse
from pathlib import Path
import gzip
import hashlib
import json
import re

ASSETS = [
    ("HomeStyle", "home-style.html"),
    ("HomeScript", "home-script.html"),
    ("ActiveTaskStyle", "active-task-style.html"),
    ("ActiveTaskScript", "active-task-script.html"),
    ("PauseScript", "pause-script.html"),
    ("SingleOutputForm", "single-output-form.html"),
    ("LearningStyle", "learning-style.html"),
    ("LearningScript", "learning-script.html"),
    ("RecordsStyle", "records-style.html"),
    ("EventsStyle", "events-style.html"),
]


def byte_array(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
    return "\n".join(rows)


def render(root: Path) -> tuple[str, str]:
    fragments = []
    assets = []
    for enum_name, filename in ASSETS:
        raw = (root / "web-src" / filename).read_text()

        def externalize(match: re.Match) -> str:
            tag, body = match.group(1), match.group(2)
            payload = body.encode("utf-8")
            compressed = bytearray(gzip.compress(payload, compresslevel=9, mtime=0))
            compressed[9] = 255  # deterministic gzip OS byte
            if gzip.decompress(compressed) != payload:
                raise RuntimeError(f"compression round trip failed: {filename}")
            extension = "js" if tag == "script" else "css"
            path = f"/irrigation/assets/{enum_name}.{extension}"
            version = hashlib.sha256(payload).hexdigest()[:12]
            name = f"k{enum_name}{extension.upper()}"
            content_type = "application/javascript; charset=utf-8" if tag == "script" else "text/css; charset=utf-8"
            assets.append((name, path, content_type, bytes(compressed)))
            if tag == "script":
                return f'<script src="{path}?v={version}"></script>'
            return f'<link rel="stylesheet" href="{path}?v={version}">'

        fragment = re.sub(r"<(script|style)>(.*?)</\1>", externalize, raw, flags=re.S)
        fragments.append((enum_name, fragment))

    header = """#pragma once

#include <cstdint>

namespace IrrigationWebAssets {

enum class Asset : uint8_t {
"""
    header += "".join(f"    {name},\n" for name, _ in fragments)
    header += """};

bool registerAssets();
bool send(Asset asset);

}  // namespace IrrigationWebAssets
"""
    source = """// Generated by scripts/generate_web_assets.py. Do not edit manually.
#include "IrrigationWebAssets.h"
#include <Esp32Base.h>

namespace IrrigationWebAssets {
namespace {
"""
    for name, _, _, compressed in assets:
        source += f"const uint8_t {name}[] = {{\n{byte_array(compressed)}\n}};\n\n"
    source += "}  // namespace\n\nbool registerAssets() {\n    return "
    source += " &&\n           ".join(
        f'Esp32BaseWeb::addStaticAsset("{path}", "{kind}", {name}, sizeof({name}), 86400, true, true)'
        for name, path, kind, _ in assets)
    source += ";\n}\n\nbool send(Asset asset) {\n    switch (asset) {\n"
    for name, fragment in fragments:
        source += f"        case Asset::{name}:\n            Esp32BaseWeb::sendChunk({json.dumps(fragment, ensure_ascii=False)});\n            return true;\n"
    source += "    }\n    return false;\n}\n\n}  // namespace IrrigationWebAssets\n"
    return header, source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    generated = root / "src" / "irrigation" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    targets = {
        generated / "IrrigationWebAssets.h": None,
        generated / "IrrigationWebAssets.cpp": None,
    }
    header, source = render(root)
    targets[generated / "IrrigationWebAssets.h"] = header
    targets[generated / "IrrigationWebAssets.cpp"] = source

    stale = [path for path, content in targets.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            print("generated Web assets are stale: " + ", ".join(str(path) for path in stale))
            return 1
        print("generated Web assets are current")
        return 0

    for path, content in targets.items():
        path.write_text(content)
    print("generated " + ", ".join(str(path) for path in targets))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
