#!/usr/bin/env python3
"""Generate compressed, byte-exact local Web fragments for the irrigation firmware."""

from __future__ import annotations

import argparse
from pathlib import Path
import zlib

ASSETS = [
    ("HomeStyle", "home-style.html"),
    ("HomeScript", "home-script.html"),
    ("ActiveTaskStyle", "active-task-style.html"),
    ("ActiveTaskScript", "active-task-script.html"),
    ("PauseScript", "pause-script.html"),
    ("SingleOutputForm", "single-output-form.html"),
    ("LearningStyle", "learning-style.html"),
    ("LearningScript", "learning-script.html"),
    ("RecordsStyle", "records-style.html"),
    ("EventsStyle", "events-style.html"),
]


def byte_array(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
    return "\n".join(rows)


def render(root: Path) -> tuple[str, str]:
    assets = []
    maximum_size = 0
    for enum_name, filename in ASSETS:
        raw = (root / "web-src" / filename).read_bytes()
        compressed = zlib.compress(raw, level=9)
        if zlib.decompress(compressed) != raw:
            raise RuntimeError(f"compression round trip failed: {filename}")
        assets.append((enum_name, raw, compressed))
        maximum_size = max(maximum_size, len(raw))

    header = """#pragma once

#include <cstdint>

namespace IrrigationWebAssets {

enum class Asset : uint8_t {
"""
    header += "".join(f"    {name},\n" for name, _, _ in assets)
    header += """};

bool send(Asset asset);

}  // namespace IrrigationWebAssets
"""

    source = """// Generated by scripts/generate_web_assets.py. Do not edit manually.
#include "IrrigationWebAssets.h"

#include <Esp32Base.h>
#include <rom/miniz.h>

#include <cstddef>
#include <cstdint>

namespace IrrigationWebAssets {
namespace {

struct Descriptor {
    const uint8_t* compressed;
    uint32_t compressedSize;
    uint32_t uncompressedSize;
};

"""
    for name, _, compressed in assets:
        source += f"const uint8_t k{name}[] = {{\n{byte_array(compressed)}\n}};\n\n"
    source += "const Descriptor kDescriptors[] = {\n"
    for name, raw, compressed in assets:
        source += f"    {{k{name}, {len(compressed)}U, {len(raw)}U}},\n"
    source += f"}};\n\nuint8_t g_output[{maximum_size + 1}U];\n\n}}  // namespace\n\n"
    source += """bool send(Asset asset) {
    const uint8_t index = static_cast<uint8_t>(asset);
    if (index >= sizeof(kDescriptors) / sizeof(kDescriptors[0])) return false;
    const Descriptor& descriptor = kDescriptors[index];
    const size_t outputSize = tinfl_decompress_mem_to_mem(
        g_output,
        descriptor.uncompressedSize,
        descriptor.compressed,
        descriptor.compressedSize,
        TINFL_FLAG_PARSE_ZLIB_HEADER | TINFL_FLAG_USING_NON_WRAPPING_OUTPUT_BUF);
    if (outputSize == TINFL_DECOMPRESS_MEM_TO_MEM_FAILED ||
        outputSize != descriptor.uncompressedSize) {
        ESP32BASE_LOG_E("irrigation_web", "asset_decompress_failed asset=%u size=%lu",
                        static_cast<unsigned>(index),
                        static_cast<unsigned long>(outputSize));
        return false;
    }
    g_output[outputSize] = 0;
    Esp32BaseWeb::sendChunk(reinterpret_cast<const char*>(g_output));
    return true;
}

}  // namespace IrrigationWebAssets
"""
    return header, source


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    generated = root / "src" / "irrigation" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    targets = {
        generated / "IrrigationWebAssets.h": None,
        generated / "IrrigationWebAssets.cpp": None,
    }
    header, source = render(root)
    targets[generated / "IrrigationWebAssets.h"] = header
    targets[generated / "IrrigationWebAssets.cpp"] = source

    stale = [path for path, content in targets.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            print("generated Web assets are stale: " + ", ".join(str(path) for path in stale))
            return 1
        print("generated Web assets are current")
        return 0

    for path, content in targets.items():
        path.write_text(content)
    print("generated " + ", ".join(str(path) for path in targets))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
