#!/usr/bin/env python3

import argparse
import hashlib
import json
import sys
from pathlib import Path


FIXTURE_RELATIVE_PATH = Path(
    "device-types/irrigation-controller/test/fixtures/platform-command-vectors.json"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "test/test_platform_protocol/generated/platform_command_vectors.h"
)


def _arguments():
    parser = argparse.ArgumentParser(
        description="Sync the controlled irrigation platform command vectors for native tests."
    )
    parser.add_argument(
        "--lab-root",
        required=True,
        type=Path,
        help="iot-device-lab repository root containing the controlled fixture",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed generated header differs from the fixture",
    )
    return parser.parse_args()


def _payload(case):
    has_json = "payload" in case
    has_hex = "payloadHex" in case
    if has_json == has_hex:
        raise ValueError("case %s must contain exactly one payload form" % case.get("id"))
    if has_hex:
        return bytes.fromhex(case["payloadHex"])
    return json.dumps(
        case["payload"],
        ensure_ascii=False,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _cpp_string(value):
    return json.dumps(value, ensure_ascii=True)


def _byte_array(name, payload):
    values = ["0x%02x" % value for value in payload]
    lines = []
    for index in range(0, len(values), 16):
        lines.append("    " + ", ".join(values[index : index + 16]) + ",")
    return "static const uint8_t %s[] = {\n%s\n};" % (name, "\n".join(lines))


def _render(raw, source_sha256):
    fixture = json.loads(raw.decode("utf-8"))
    if fixture.get("schemaVersion") != "1" or not isinstance(fixture.get("cases"), list):
        raise ValueError("unsupported platform command fixture schema")
    cases = fixture["cases"]
    payloads = []
    rows = []
    for index, case in enumerate(cases):
        if not isinstance(case.get("id"), str) or not isinstance(case.get("topic"), str):
            raise ValueError("fixture case identity/topic is invalid at index %d" % index)
        if not isinstance(case.get("qos"), int) or not isinstance(case.get("retain"), bool):
            raise ValueError("fixture transport is invalid for %s" % case["id"])
        expected = case.get("expected")
        if not isinstance(expected, dict) or not isinstance(expected.get("accepted"), bool):
            raise ValueError("fixture expectation is invalid for %s" % case["id"])
        payload = _payload(case)
        name = "kPayload%u" % index
        payloads.append(_byte_array(name, payload))
        rows.append(
            "    {%s, %s, %u, %s, %s, sizeof(%s), %s},"
            % (
                _cpp_string(case["id"]),
                _cpp_string(case["topic"]),
                case["qos"],
                "true" if case["retain"] else "false",
                name,
                name,
                "true" if expected["accepted"] else "false",
            )
        )
    return """// Generated by scripts/sync_platform_command_vectors.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace IrrigationPlatformCommandFixtures {

static constexpr char kSourceFixtureSha256[] = %s;
static constexpr char kSchemaVersion[] = %s;
static constexpr char kTypeKey[] = %s;
static constexpr char kModelKey[] = %s;
static constexpr char kDeviceId[] = %s;

struct PlatformCommandVector {
    const char* id;
    const char* topic;
    uint8_t qos;
    bool retain;
    const uint8_t* payload;
    std::size_t payloadLength;
    bool accepted;
};

%s

static const PlatformCommandVector kCases[] = {
%s
};

static constexpr std::size_t kCaseCount = sizeof(kCases) / sizeof(kCases[0]);

}  // namespace IrrigationPlatformCommandFixtures
""" % (
        _cpp_string(source_sha256),
        _cpp_string(fixture["schemaVersion"]),
        _cpp_string(fixture.get("typeKey", "")),
        _cpp_string(fixture.get("modelKey", "")),
        _cpp_string(fixture.get("deviceId", "")),
        "\n\n".join(payloads),
        "\n".join(rows),
    )


def main():
    arguments = _arguments()
    source = (arguments.lab_root / FIXTURE_RELATIVE_PATH).resolve()
    if not source.is_file():
        raise FileNotFoundError("controlled fixture not found: %s" % source)
    raw = source.read_bytes()
    source_sha256 = hashlib.sha256(raw).hexdigest()
    case_count = len(json.loads(raw.decode("utf-8"))["cases"])
    generated = _render(raw, source_sha256)
    output = arguments.output.resolve()
    if arguments.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != generated:
            print(
                "platform command fixture drift: run sync_platform_command_vectors.py without --check",
                file=sys.stderr,
            )
            return 1
        print(
            "platform command fixtures current: cases=%d sha256=%s"
            % (case_count, source_sha256)
        )
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(generated, encoding="utf-8", newline="\n")
    temporary.replace(output)
    print(
        "platform command fixtures synced: output=%s cases=%d sha256=%s"
        % (output, case_count, source_sha256)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
