#ifndef IRRIGATION_SLAVE_BOARD_CONFIG_H
#define IRRIGATION_SLAVE_BOARD_CONFIG_H

#define STC8H_CHIP_STC8H1K08 0
#define STC8H_CHIP_STC8H8K64U 1

#ifndef STC8H_SYSCLK_HZ
#define STC8H_SYSCLK_HZ 11059200UL
#endif

#ifndef STC8H_UART1_BAUD
#define STC8H_UART1_BAUD 115200UL
#endif

#ifndef STC8H_ADC_BITS
#define STC8H_ADC_BITS 12u
#endif

#ifndef STC8H_ADC_CHIP_CHANNEL_MASK
#define STC8H_ADC_CHIP_CHANNEL_MASK 0xFFFFu
#endif

#ifndef STC8H_ADC_CHANNEL_MASK
#define STC8H_ADC_CHANNEL_MASK STC8H_ADC_CHIP_CHANNEL_MASK
#endif

#endif

