#ifndef IRRIGATION_SLAVE_BOARD_PINS_H
#define IRRIGATION_SLAVE_BOARD_PINS_H

#define BOARD_RS485_UART STC8H_UART1

#define BOARD_RS485_DIR_PORT 4u
#define BOARD_RS485_DIR_PIN  1u
#define BOARD_RS485_DIR_MASK 0x02u

#define BOARD_PWM_COUNT 8u

#define BOARD_DIP0_PORT 2u
#define BOARD_DIP0_PIN  1u
#define BOARD_DIP1_PORT 2u
#define BOARD_DIP1_PIN  3u
#define BOARD_DIP2_PORT 2u
#define BOARD_DIP2_PIN  5u
#define BOARD_DIP3_PORT 2u
#define BOARD_DIP3_PIN  7u

#define BOARD_ADC_VIN_CHANNEL 0u
#define BOARD_ADC_SEN1_CHANNEL 1u
#define BOARD_ADC_SEN2_CHANNEL 3u

#define BOARD_INPUT1_PORT 3u
#define BOARD_INPUT1_PIN  4u
#define BOARD_INPUT2_PORT 3u
#define BOARD_INPUT2_PIN  5u
#define BOARD_INPUT3_PORT 0u
#define BOARD_INPUT3_PIN  4u
#define BOARD_INPUT4_PORT 0u
#define BOARD_INPUT4_PIN  6u

#define BOARD_DRY_OUT1_PORT 5u
#define BOARD_DRY_OUT1_PIN  3u

#endif
